### ISSUE TITLE
resourceRequiresConsent error when trying to use SSO

### ISSUE THREAD

**Issue by lzgrzebski** [ydogandjiev/taskmeow#25]
Hi. Im following this article where this repo is linked https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/auth-aad-sso

And when Im uploading the app to the teams Im getting `Error description:AADSTS65001: The user or administrator has not consented to use the application with ID '5e3ce6c0-2b1f-4285-8d4b-75ee78787346' named 'Microsoft Teams Web Client'. Send an interactive authorization request for this user and resource.` and `resourceRequiresConsent` and this point I was expecting to get the native teams popup to get user consent? Am I missing smth? AAD app is configured based on this tutorial and Im calling `microsoftTeams.authentication.getAuthToken` do I still need to use adal.js when the `getAuthToken` is rejecting the Promise?

**Comment by ydogandjiev** [comment]
Hey @lzgrzebski , I've got a couple of questions for you:
1. Did you switch your Teams Client to our developer preview ring as per the instructions here:
https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview-intro#enable-developer-preview
2. Did you add the Teams client IDs to your AAD app's pre-authorized applications list:
    - 1fec8e78-bce4-4aaf-ab1b-5451cc387264 (Teams mobile/desktop application)
    - 5e3ce6c0-2b1f-4285-8d4b-75ee78787346 (Teams web application)

![image](https://user-images.githubusercontent.com/3357245/70735241-a7a40980-1cc2-11ea-828c-b06570614bab.png)

**Comment by synth** [comment]
I had this issue and switching to developer preview fixed it for me. Any idea when this will go to general availability?

**Comment by ydogandjiev** [comment]
@synth, unfortunately I cannot give you an exact date but we've finished development of the feature and are trying to roll it out as soon as possible. Will let you know once it's reached general availability.
