### ISSUE TITLE
Question and possible issue

### ISSUE THREAD

**Issue by icatchx22i** [ydogandjiev/taskmeow#28]
I have stumbled upon this app in my quest to understand AAD auth within MS Teams tab.  I am not sure if my test scenario is valid but want to ask about it still as i experienced the same behavior with my code: 

The app opens a popup when used within a browser but, as soon as its in MSTeams Tab instead of a popup, a new Tab is opened in a Browser then the authentication happens there and doesnt make it back to MSTeams. 

I have tested this TaskMeow by creating a Website tab of the Demo app and i see the same behavior there. As soon as i click on the login a new tab is opened in my computers' default browser. Is this a valid test scenario? an issue with Teams?

**Comment by ydogandjiev** [comment]
Hey @icatchx22i, the authentication support is built to work when the web app is integrated with Teams via the public platform documented here:
https://docs.microsoft.com/en-us/microsoftteams/platform/overview

To see it in action just sideload the following app package into Teams:
https://github.com/ydogandjiev/taskmeow/raw/master/manifest/prod/taskmeow-prod.zip

You can do that following the instructions here:
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload
