### ISSUE TITLE
How do you ensure the user is in teams ?

### ISSUE THREAD

**Issue by TechWatching** [ydogandjiev/taskmeow#32]
I want to use teams sso as well for my teams tab application so your taskmeow is a perfect example for that. However I don't understand how do you check wether the application executes in teams or not.

I have seen that you are checking a query param inTeams, does the url always have this query param when executing in teams ? How will `microsoftTeams.authentication.getAuthToken` behaves outside a teams context ?  

What I want is for my application only to works inside teams to that anyone accessing directly my web application through a browser won't have access to the data. Any idea how ?

**Comment by icatchx22i** [comment]
@TechWatching I believe the way to do this is by using microsoftTeams.getContext(function(context) { /* ... */ }). function in the SDK. It resolves to the metadata you'd get only from within Teams. Although, as the docs warn, this is not a secure replacement for full authentication.

ref: https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/access-teams-context

**Comment by TechWatching** [comment]
Thanks for your answer. I finally opted to follow what you have done in your repository. 
That is encapsulate the `getToken` method in a promise and set the state in case of success. That allows me to check the state to know if I have to display an error message (when token was not retrieved so the user is not logged in teams) or display my page and data (user is logged in and accessing web app in teams).
